home:
    path: /
    controller: App\Controller\HomeController

trick:
    path: /trick/{id}
    controller: App\Controller\TrickController

controllers:
    resource: ../src/Controller/
    type: attribute
